# Generated by Django 4.2.3 on 2023-07-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='apellidos')),
                ('genero', models.CharField(choices=[('h', 'Hombre'), ('M', 'Mujer')], max_length=50, verbose_name='genero')),
                ('telefono', models.CharField(max_length=50, verbose_name='telefono')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
            ],
        ),
    ]
