# Generated by Django 4.2.3 on 2023-07-21 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aulas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreAula",
                    models.CharField(max_length=50, verbose_name="nombreAula"),
                ),
                ("capacidadAula", models.IntegerField(verbose_name="capacidadAula")),
                ("numeroAula", models.IntegerField(verbose_name="numeroAula")),
            ],
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreCarrera",
                    models.CharField(max_length=50, verbose_name="nombreCarrera"),
                ),
                (
                    "anioCarrera",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="aniocarrera"
                    ),
                ),
                (
                    "numeroTotalCiclos",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="numeroTotalCiclos"
                    ),
                ),
                (
                    "codigoCarrera",
                    models.CharField(max_length=50, verbose_name="codigoCarrera"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ciclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroCiclo", models.IntegerField(verbose_name="numeroCiclo")),
                (
                    "nombreCiclo",
                    models.CharField(max_length=50, verbose_name="nombreCiclo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Facultad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreFacultad",
                    models.CharField(max_length=100, verbose_name="nombreFacultad"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=50, verbose_name="descripcion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Funciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreFunciones",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="nombreFunciones",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreHorario",
                    models.CharField(max_length=25, verbose_name="nombreHorario"),
                ),
                (
                    "aulas",
                    models.ManyToManyField(
                        related_name="materia_aulas", to="administrador.aulas"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="horasHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreHora",
                    models.CharField(max_length=50, verbose_name="nombreHora"),
                ),
                ("dia", models.DateField(max_length=50, verbose_name="dia")),
                (
                    "horaInicio",
                    models.TimeField(blank=True, null=True, verbose_name="horaInicio"),
                ),
                (
                    "horaFin",
                    models.TimeField(blank=True, null=True, verbose_name="horaFin"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Malla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campus",
                    models.CharField(
                        blank=True,
                        choices=[("G", "Guayaquil"), ("Q", "Quito"), ("l", "Loja")],
                        max_length=50,
                        null=True,
                        verbose_name="campus",
                    ),
                ),
                (
                    "nombreMalla",
                    models.CharField(max_length=50, verbose_name="nombreMalla"),
                ),
                (
                    "anioMalla",
                    models.CharField(
                        choices=[
                            ("2019", "2019"),
                            ("2020", "2020"),
                            ("2021", "2021"),
                            ("2022", "2023"),
                        ],
                        max_length=50,
                        verbose_name="anioMalla",
                    ),
                ),
                (
                    "carrera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrador.carrera",
                        verbose_name="carrera",
                    ),
                ),
                (
                    "ciclo",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="malla_materia",
                        to="administrador.ciclo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duracionClase", models.IntegerField(verbose_name="duracionClase")),
                (
                    "nombreMateria",
                    models.CharField(max_length=50, verbose_name="nombreMateria"),
                ),
                (
                    "ciclo",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="administrador.ciclo",
                        verbose_name="ciclo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Paralelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroParalelo", models.IntegerField(verbose_name="numeroParalelo")),
                (
                    "numeroEstudiantes",
                    models.IntegerField(verbose_name="numeroEstudiantes"),
                ),
                (
                    "nombreParalelo",
                    models.CharField(max_length=50, verbose_name="nombreParalelo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=50, verbose_name="nombres")),
                (
                    "apellidos",
                    models.CharField(max_length=50, verbose_name="apellidos"),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[("h", "Hombre"), ("M", "Mujer")],
                        max_length=50,
                        verbose_name="genero",
                    ),
                ),
                ("telefono", models.CharField(max_length=50, verbose_name="telefono")),
                ("email", models.CharField(max_length=50, verbose_name="email")),
            ],
        ),
        migrations.CreateModel(
            name="Coordinador",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="administrador.persona",
                    ),
                ),
                (
                    "codigoCoordinador",
                    models.CharField(max_length=50, verbose_name="codigoCoordinador"),
                ),
            ],
            bases=("administrador.persona",),
        ),
        migrations.CreateModel(
            name="Estudiante",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="administrador.persona",
                    ),
                ),
                (
                    "nivelIngles",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Nivel1"),
                            ("2", "Nivel2"),
                            ("3", "Nivel3"),
                            ("4", "Nivel4"),
                            ("5", "Nivel5"),
                            ("6", "Nivel6"),
                            ("C", "Completado"),
                            ("N", "Ninguno"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="nivelIngles",
                    ),
                ),
                ("numeroCarnet", models.IntegerField(verbose_name="numeroCarnet")),
            ],
            bases=("administrador.persona",),
        ),
        migrations.CreateModel(
            name="PeriodoAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaInicio", models.DateField(verbose_name="fechaInicio")),
                ("fechaFin", models.DateField(verbose_name="fechaFin")),
                (
                    "nombrePeriodoAcademico",
                    models.CharField(
                        max_length=50, verbose_name="nombrePeriodoAcademico"
                    ),
                ),
                (
                    "ciclo",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="administrador.ciclo",
                        verbose_name="Ciclos",
                    ),
                ),
                (
                    "malla",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="administrador.malla",
                        verbose_name="Mallas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ofertador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreOfertador",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="nombreOfertador",
                    ),
                ),
                ("fechaOfertada", models.DateField(verbose_name="fechaOfertada")),
                (
                    "ciclo",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="ofertador_ciclo",
                        to="administrador.ciclo",
                    ),
                ),
                (
                    "malla",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="ofertador_malla",
                        to="administrador.malla",
                    ),
                ),
                (
                    "periodoAcademico",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ofertador_periodoAcademico",
                        to="administrador.periodoacademico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="materia_horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horaInicio",
                    models.TimeField(blank=True, null=True, verbose_name="horaInicio"),
                ),
                (
                    "horaFin",
                    models.TimeField(blank=True, null=True, verbose_name="horaFin"),
                ),
                (
                    "Paralelo",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="aulas_paralelo",
                        to="administrador.paralelo",
                    ),
                ),
                (
                    "horario",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="materia_horario",
                        to="administrador.horario",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrador.materia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="horario",
            name="horario",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="aulas_horario",
                to="administrador.horashorario",
            ),
        ),
        migrations.AddField(
            model_name="horario",
            name="materia",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="materia_aulas",
                to="administrador.materia",
            ),
        ),
        migrations.AddField(
            model_name="carrera",
            name="facultad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="administrador.facultad",
            ),
        ),
        migrations.CreateModel(
            name="materia_estudiante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "materiaAprobada",
                    models.CharField(
                        choices=[("s", "Si"), ("N", "No"), ("P", "Pendiente")],
                        max_length=50,
                        verbose_name="materiaAprobada",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrador.materia",
                    ),
                ),
                (
                    "estudiante",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="materia_estudiante",
                        to="administrador.estudiante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="administrador.persona",
                    ),
                ),
                (
                    "codigoDocente",
                    models.CharField(max_length=50, verbose_name="codigoDocente"),
                ),
                (
                    "especialidad",
                    models.CharField(max_length=50, verbose_name="especialidad"),
                ),
                (
                    "funciones",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="administrador.funciones",
                        verbose_name="funciones",
                    ),
                ),
                (
                    "materia",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="docente_materia",
                        to="administrador.materia",
                    ),
                ),
            ],
            bases=("administrador.persona",),
        ),
        migrations.AddField(
            model_name="carrera",
            name="coordinador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="administrador.coordinador",
            ),
        ),
    ]
