# Generated by Django 4.2.3 on 2023-07-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materia_estudiante",
            name="materia",
        ),
        migrations.AddField(
            model_name="materia_estudiante",
            name="materia",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="materia_estudiante",
                to="administrador.materia",
            ),
        ),
    ]
