# Generated by Django 4.2.3 on 2023-07-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrador.persona')),
                ('codigoDocente', models.CharField(max_length=50, verbose_name='codigoDocente')),
                ('especialidad', models.CharField(max_length=50, verbose_name='especialidad')),
                ('funciones', models.CharField(choices=[('Docencia', 'Docente'), ('Investigacion', 'Investigacion'), ('Vinculacion', 'Vinculacion'), ('Gestion', 'Gestion')], max_length=50, verbose_name='funciones')),
            ],
            bases=('administrador.persona',),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrador.persona')),
                ('numeroCarnet', models.CharField(max_length=50, verbose_name='numeroCarnet')),
            ],
            bases=('administrador.persona',),
        ),
    ]
