# Generated by Django 4.2.3 on 2023-07-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0002_docente_estudiante"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aulas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreAula",
                    models.CharField(max_length=50, verbose_name="nombreAula"),
                ),
                ("capacidadAula", models.IntegerField(verbose_name="capacidadAula")),
                ("numeroAula", models.IntegerField(verbose_name="numeroAula")),
                ("horaInicio", models.TimeField(verbose_name="horaInicio")),
                ("horaFin", models.TimeField(verbose_name="horaFin")),
            ],
        ),
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreCarrera",
                    models.CharField(max_length=50, verbose_name="nombreCarrera"),
                ),
                (
                    "duracionCarrera",
                    models.IntegerField(verbose_name="duracionCarrera"),
                ),
                (
                    "codigoCarrera",
                    models.CharField(max_length=50, verbose_name="codigoCarrera"),
                ),
                (
                    "tipoAsignatura",
                    models.CharField(max_length=50, verbose_name="tipoAsignatura"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ciclo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroCiclo", models.IntegerField(verbose_name="numeroCiclo")),
                (
                    "nombreCiclo",
                    models.CharField(max_length=50, verbose_name="nombreCiclo"),
                ),
                ("fechaInicio", models.DateField(verbose_name="fechaInicio")),
                ("fechaFin", models.DateField(verbose_name="fechaFin")),
            ],
        ),
        migrations.CreateModel(
            name="Coordinador",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="administrador.persona",
                    ),
                ),
                (
                    "codigoCoordinador",
                    models.CharField(max_length=50, verbose_name="codigoCoordinador"),
                ),
            ],
            bases=("administrador.persona",),
        ),
        migrations.CreateModel(
            name="Facultad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreFacultad",
                    models.CharField(max_length=100, verbose_name="nombreFacultad"),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=50, verbose_name="descripcion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreHorario",
                    models.CharField(max_length=25, verbose_name="nombreHorario"),
                ),
                ("diaSemana", models.DateField(verbose_name="diaSemana")),
                ("horaInicio", models.DateField(verbose_name="horaInicio")),
                ("horaFin", models.DateField(verbose_name="horaFin")),
            ],
        ),
        migrations.CreateModel(
            name="Malla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreMalla",
                    models.CharField(max_length=50, verbose_name="nombreMalla"),
                ),
                (
                    "anioMalla",
                    models.CharField(
                        choices=[
                            ("2019", "2019"),
                            ("2020", "2020"),
                            ("2021", "2021"),
                            ("2022", "2023"),
                        ],
                        max_length=50,
                        verbose_name="anioMalla",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duracionClase", models.IntegerField(verbose_name="duracionClase")),
                (
                    "numeroEstudiante",
                    models.IntegerField(verbose_name="numeroEstudiante"),
                ),
                ("horasClase", models.IntegerField(verbose_name="numeroEstudiantes")),
                (
                    "nombreMateria",
                    models.CharField(max_length=50, verbose_name="nombreMateria"),
                ),
                (
                    "materiaAprobada",
                    models.BooleanField(verbose_name="materiaAprobada"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ofertador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaOfertada", models.DateField(verbose_name="fechaOfertada")),
            ],
        ),
        migrations.CreateModel(
            name="Paralelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numeroParalelo", models.IntegerField(verbose_name="numeroParalelo")),
                (
                    "numeroEstudiantes",
                    models.IntegerField(verbose_name="numeroEstudiantes"),
                ),
                (
                    "nombreParalelo",
                    models.CharField(max_length=50, verbose_name="nombreParalelo"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PeriodoAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaInicio", models.DateField(verbose_name="fechaInicio")),
                ("fechaFin", models.DateField(verbose_name="fechaFin")),
                (
                    "nombrePeriodoAcademico",
                    models.CharField(
                        max_length=50, verbose_name="nombrePeriodoAcademico"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="numeroCarnet",
            field=models.IntegerField(verbose_name="numeroCarnet"),
        ),
    ]
