# Generated by Django 4.2.3 on 2023-07-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0005_remove_aulas_modalidad_docente_limitehoras"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materia_estudiante",
            name="materiaAprobada",
            field=models.CharField(
                choices=[("s", "Si"), ("N", "No"), ("SIN", "Sin Cursar")],
                max_length=50,
                verbose_name="materiaAprobada",
            ),
        ),
    ]
