# Generated by Django 4.2.3 on 2023-07-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrador", "0006_alter_materia_estudiante_materiaaprobada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrera",
            name="nombreCarrera",
            field=models.CharField(max_length=100, verbose_name="nombreCarrera"),
        ),
        migrations.AlterField(
            model_name="horario",
            name="nombreHorario",
            field=models.CharField(max_length=100, verbose_name="nombreHorario"),
        ),
        migrations.AlterField(
            model_name="materia_estudiante",
            name="materiaAprobada",
            field=models.CharField(
                choices=[("s", "Si"), ("N", "No"), ("Sin", "Sin Cursar")],
                max_length=50,
                verbose_name="materiaAprobada",
            ),
        ),
    ]
